
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from recipe import views

# DefaultRouter is a feature of the django rest framework
# that will automatically generate the URLs for our viewset
# > so when you have a viewset
# you may have multiple URLs associated with that 1 viewset
# e.g.
# /api/recipe/tags,
# /api/recipe/tags/1/ (1,2,3,... to retrieve specific id)
# hence the default router automatically registers
# the appropriate URLs for allof the actions in our viewset
router = DefaultRouter()

# register our viewset in our router
router.register('tags', views.TagViewSet)
router.register('ingredients', views.IngredientViewSet)
router.register('recipe', views.RecipeViewSet)


app_name = 'recipe'

urlpatterns = [
    # '' means any path that matches our recipe app
    # pass in our router url
    # so all the urls generated by our default router
    # will then be included in our URLs patterns
    # as well as feature viewsets
    path('', include(router.urls))
]
